FROM eclipse-temurin:23-jdk

# Cài curl thêm vào danh sách
RUN apt-get update && apt-get install -y wget unzip curl \
 && wget https://archive.apache.org/dist/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.zip \
 && unzip apache-maven-3.9.3-bin.zip -d /opt \
 && ln -s /opt/apache-maven-3.9.3 /opt/maven \
 && ln -s /opt/maven/bin/mvn /usr/bin/mvn \
 && rm apache-maven-3.9.3-bin.zip \
 && apt-get clean

WORKDIR /app

CMD ["mvn", "spring-boot:run"]
